services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "81:80"

  backend:
    container_name: backend
    image: node:22
    ports:
     - "82:9000"
    working_dir: /usr/src/app
    command: sh -c "
      chmod +x startup.sh &&
      ./startup.sh"
    links:
     - database
    volumes:
     - ./backend:/usr/src/app:rw
    environment:
     - JWT_SECRET=secretkey
     - PORT=9000
     - MONGO_URI=mongodb://root:password@database:27017/database?authSource=admin
     - NODE_ENV=production

  database:
    container_name: database
    image: mongo:latest
    ports:
     - "83:27017"
    environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: password
     MONGO_INITDB_DATABASE: database
    volumes:
     - ./data:/data/db