# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code of the frontend/backend and run tests on both

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    options:
      --health-cmd="curl --silent --fail localhost:27017 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database

  backend:
    name: Backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - name: Install & Build Backend
      run: |
        cd backend
        npm ci
        npm run build --if-present
    - name: Backend Unit Tests
      run: |
        cd backend
        npx mocha -ui tdd 'tests/unitTests/*.js'
    - name: Backend Integration Tests
      run: |
        cd backend
        npx mocha -ui tdd 'tests/integrationTests/*.js'

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install & Build Frontend
      run: |
        cd frontend
        npm ci
        npm run build --if-present
    - name: Test Frontend
      run: |
        cd frontend
        npx mocha -ui tdd 'tests/*'
